### ISSUE TITLE
curl data should be convert to http post rather then get

### ISSUE THREAD

**Issue by williamhatch** [dcb9/curl2httpie#12]
e.g: 
curl 'https://xxx/v1/tokens' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0' -H 'Accept: application/vnd.api+json' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/vnd.api+json' -H 'Origin: https://xxx' -H 'Connection: keep-alive' -H 'Referer: https://xxx' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data '{"auth":{"email":"xxx","password":"xxx"}}'

should be HTTP POST ... now is GET

**Comment by dcb9** [comment]
Thanks for your opening the issue! and sorry for being late.
