### ISSUE TITLE
Is there a command-line option? Proxy at work blocking the webpage.

### ISSUE THREAD

**Issue by CsBigDataHub** [dcb9/curl2httpie#13]
Is there a command-line option?
Proxy at work blocking the webpage.

**Comment by dcb9** [comment]
Yeah, download the binary of your platform from [releases](https://github.com/dcb9/curl2httpie/releases), run the command directly from you terminal, like below.

```
$ ~/Downloads/curl2httpie_v1.3_darwin_amd64/curl2httpie curl google.com
http GET 'google.com'
```
