### ISSUE TITLE
protocol conversion and -k

### ISSUE THREAD

**Issue by greenseeker** [dcb9/curl2httpie#17]
Thanks a lot for this tool. I had a working curl example that I just couldn't get working under httpie, and this tool did guide me to my mistake.

There are 2 things I noticed which can be improved, however. This was my input:
`curl -kX POST -d 'username=admin&password=12345' https://example.com/api/tokens`

This was the output:
`http --form POST 'https://example.com/api/tokens' 'username=admin' 'password=12345'`

First thing, the httpie convention is to not use the protocol in the URL, but by using the appropriate `http`/`https` command:
`https --form POST 'example.com/api/tokens' 'username=admin' 'password=12345'`

Second thing, there was a message at the bottom of the page:
> skipped: option "insecure" is not supported

The httpie equivalent to curl's `-k` is `--verify=no`.

**Comment by dcb9** [comment]
Thanks for your contribution, all of them are good suggestion, so I have implemented them, you can check it out! Wish you like it.
