### ISSUE TITLE
Query parameters are not quoted

### ISSUE THREAD

**Issue by wadouk** [dcb9/curl2httpie#4]
`curl "https://httpbin.org/get?1=2&3=4"`
is converted to 
`http GET https://httpbin.org/get?1=2&3=4`

which will result to
```
^C
[1]+  Done
```

Expected
`http GET "https://httpbin.org/get?1=2&3=4"`

Single quoted could be a choice too

**Comment by dcb9** [comment]
it has been implemented now by f97845553ddf379a121cc743caae5777d2cf09b9
